#!/bin/bash
if [ "$MASTER_ENGINE_NAME" ]; then
	echo "find this node as a master node"
	if [ -f ${SYMMETRICDS_HOME}/tmp/init.sql ]; then
        echo "creating sym-tables ..."
		${SYMMETRICDS_HOME}/bin/symadmin --engine ${MASTER_ENGINE_NAME} create-sym-tables
        echo "inserting init.sql ..."
		${SYMMETRICDS_HOME}/bin/dbimport --engine ${MASTER_ENGINE_NAME} ${SYMMETRICDS_HOME}/tmp/init.sql
	    rm ${SYMMETRICDS_HOME}/tmp/init.sql
	    echo "init.sql is deleted"
    fi
fi
echo "starting symmetric-ds ..."
exec ${SYMMETRICDS_HOME}/bin/sym
sym_pid=$!

wait
